//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace CoursewareUploadHelper.Entity.Courseware
{

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_resource_tag_ref")]
	public partial class TResourceTagRef {

	    [JsonProperty, Column(Name = "resource_id")]
	    public long ResourceId
	    {
	        get => _ResourceId;
	        set
	        {
	            if (_ResourceId == value) return;
	            _ResourceId = value;
	            t_course_resource = null;
	        }

	    }

	    private long _ResourceId;

	    [JsonProperty, Column(Name = "tag_id")]
	    public long TagId
	    {
	        get => _TagId;
	        set
	        {
	            if (_TagId == value) return;
	            _TagId = value;
	            t_knowledge_tag = null;
	        }
	    }

	    private long _TagId;

		[JsonProperty, Column(Name = "delete_flag")]
		public byte DeleteFlag { get; set; }

		[JsonProperty, Column(Name = "t_create", DbType = "datetime2")]
		public DateTime TCreate { get; set; }

		[JsonProperty, Column(Name = "t_modified", DbType = "datetime2")]
		public DateTime TModified { get; set; }


        #region 外键 => 导航属性，ManyToOne/OneToOne

        [Navigate("ResourceId")]
        public virtual TCourseResource t_course_resource { get; set; }

        [Navigate("TagId")]
        public virtual TKnowledgeTag t_knowledge_tag { get; set; }

        #endregion

        #region 外键 => 导航属性，ManyToMany

        #endregion
    }

}
