//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace CoursewareModifyTool.Model.Course
{

	/// <summary>
	/// 课程资源库
	/// </summary>
	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_course_resource")]
	public partial class TCourseResource {

		/// <summary>
		/// 创建人ID
		/// </summary>
		[JsonProperty, Column(Name = "create_by")]
		public long? CreateBy { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 删除标识
		/// </summary>
		[JsonProperty, Column(Name = "delete_flag")]
		public short? DeleteFlag { get; set; }

		/// <summary>
		/// 组名
		/// </summary>
		[JsonProperty, Column(Name = "group_name", DbType = "varchar(50)")]
		public string GroupName { get; set; }

		/// <summary>
		/// ID
		/// </summary>
		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 资源密级
		/// </summary>
		[JsonProperty, Column(Name = "resource_confidential", DbType = "varchar(5)")]
		public string ResourceConfidential { get; set; }

		/// <summary>
		/// 资源描述
		/// </summary>
		[JsonProperty, Column(Name = "resource_desc", DbType = "text")]
		public string ResourceDesc { get; set; }

		/// <summary>
		/// 文件扩展名
		/// </summary>
		[JsonProperty, Column(Name = "resource_extension", DbType = "varchar(20)")]
		public string ResourceExtension { get; set; }

		/// <summary>
		/// 资源名称
		/// </summary>
		[JsonProperty, Column(Name = "resource_name", DbType = "varchar(100)")]
		public string ResourceName { get; set; }

		/// <summary>
		/// 资源时长
		/// </summary>
		[JsonProperty, Column(Name = "resource_time")]
		public int? ResourceTime { get; set; }

		/// <summary>
		/// 文件扩展名：ppt,word.mp4.flv
		/// </summary>
		[JsonProperty, Column(Name = "resource_type", DbType = "varchar(5)")]
		public string ResourceType { get; set; }

		/// <summary>
		/// 资源Url
		/// </summary>
		[JsonProperty, Column(Name = "resource_url", DbType = "varchar(200)")]
		public string ResourceUrl { get; set; }

		/// <summary>
		/// 源ID
		/// </summary>
		[JsonProperty, Column(Name = "src_id")]
		public long? SrcId { get; set; }

		/// <summary>
		/// 修改人ID
		/// </summary>
		[JsonProperty, Column(Name = "update_by")]
		public long? UpdateBy { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[JsonProperty, Column(Name = "update_time")]
		public DateTime? UpdateTime { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
