//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace CoursewareModifyTool.Model.Course
{

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_course_struct")]
	public partial class TCourseStruct {

		/// <summary>
		/// 课程ID
		/// </summary>
		[JsonProperty, Column(Name = "course_id")]
		public long? CourseId { get; set; }

		/// <summary>
		/// 课程节点名称
		/// </summary>
		[JsonProperty, Column(Name = "course_node_name", DbType = "varchar(100)")]
		public string CourseNodeName { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[JsonProperty, Column(Name = "create_name", DbType = "varchar(20)")]
		public string CreateName { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 删除标识
		/// </summary>
		[JsonProperty, Column(Name = "delete_flag")]
		public short? DeleteFlag { get; set; }

		/// <summary>
		/// ID
		/// </summary>
		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 节点排序
		/// </summary>
		[JsonProperty, Column(Name = "node_sort")]
		public int? NodeSort { get; set; }

		/// <summary>
		/// 1：文件夹，2：页面
		/// </summary>
		[JsonProperty, Column(Name = "node_type", DbType = "varchar(20)")]
		public string NodeType { get; set; }

		/// <summary>
		/// 父节点ID
		/// </summary>
		[JsonProperty, Column(Name = "parent_id")]
		public long? ParentId { get; set; }

		/// <summary>
		/// 子节点下资源数量
		/// </summary>
		[JsonProperty, Column(Name = "resource_count")]
		public int? ResourceCount { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[JsonProperty, Column(Name = "update_time")]
		public DateTime? UpdateTime { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
