//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace CoursewareModifyTool.Model.Course
{

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_course")]
	public partial class TCourse {

		/// <summary>
		/// 审核日期
		/// </summary>
		[JsonProperty, Column(Name = "approval_date")]
		public DateTime? ApprovalDate { get; set; }

		/// <summary>
		/// 审核备注
		/// </summary>
		[JsonProperty, Column(Name = "approval_remarks", DbType = "varchar(1000)")]
		public string ApprovalRemarks { get; set; }

		/// <summary>
		/// 审核状态
		/// </summary>
		[JsonProperty, Column(Name = "approval_status", DbType = "varchar(5)")]
		public string ApprovalStatus { get; set; }

		/// <summary>
		/// 审核人ID
		/// </summary>
		[JsonProperty, Column(Name = "approval_user_id")]
		public long? ApprovalUserId { get; set; }

		[JsonProperty, Column(Name = "approval_user_name", DbType = "varchar(50)")]
		public string ApprovalUserName { get; set; }

		/// <summary>
		/// 审核人账号
		/// </summary>
		[JsonProperty, Column(Name = "approval_user_number", DbType = "varchar(50)")]
		public string ApprovalUserNumber { get; set; }

		/// <summary>
		/// 密级
		/// </summary>
		[JsonProperty, Column(Name = "course_confidential", DbType = "varchar(5)")]
		public string CourseConfidential { get; set; }

		/// <summary>
		/// 课时数量
		/// </summary>
		[JsonProperty, Column(Name = "course_count", DbType = "decimal(5,2)")]
		public decimal? CourseCount { get; set; }

		/// <summary>
		/// 课程描述
		/// </summary>
		[JsonProperty, Column(Name = "course_desc", DbType = "varchar(1000)")]
		public string CourseDesc { get; set; }

		/// <summary>
		/// 课程名称
		/// </summary>
		[JsonProperty, Column(Name = "course_name", DbType = "varchar(50)")]
		public string CourseName { get; set; }

		[JsonProperty, Column(Name = "create_by")]
		public long? CreateBy { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 删除标识
		/// </summary>
		[JsonProperty, Column(Name = "delete_flag")]
		public short? DeleteFlag { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 学习时长
		/// </summary>
		[JsonProperty, Column(Name = "learning_time", DbType = "decimal(5,2)")]
		public decimal? LearningTime { get; set; }

		/// <summary>
		/// 发布标识
		/// </summary>
		[JsonProperty, Column(Name = "publish_flag")]
		public short? PublishFlag { get; set; }

		/// <summary>
		/// 封面路径
		/// </summary>
		[JsonProperty, Column(Name = "thumbnail_path", DbType = "varchar(200)")]
		public string ThumbnailPath { get; set; }

		[JsonProperty, Column(Name = "update_by")]
		public long? UpdateBy { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[JsonProperty, Column(Name = "update_time")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 创建人姓名
		/// </summary>
		[JsonProperty, Column(Name = "user_name", DbType = "varchar(50)")]
		public string UserName { get; set; }

		/// <summary>
		/// 账号
		/// </summary>
		[JsonProperty, Column(Name = "user_number", DbType = "varchar(50)")]
		public string UserNumber { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
