//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace CoursewareModifyTool.Model.Course
{

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_struct_resource")]
	public partial class TStructResource {

		/// <summary>
		/// 课程资源ID
		/// </summary>
		[JsonProperty, Column(Name = "course_resouce_id")]
		public long? CourseResouceId { get; set; }

		/// <summary>
		/// 课程结构ID
		/// </summary>
		[JsonProperty, Column(Name = "course_struct_id")]
		public long? CourseStructId { get; set; }

		[JsonProperty, Column(Name = "delete_flag")]
		public short? DeleteFlag { get; set; }

		/// <summary>
		/// ID
		/// </summary>
		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		[JsonProperty, Column(Name = "t_create")]
		public DateTime? TCreate { get; set; }

		[JsonProperty, Column(Name = "t_modified")]
		public DateTime? TModified { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
