//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace CoursewareModifyTool.Model.Courseware {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_course_resource")]
	public partial class TCourseResource {

		[JsonProperty, Column(Name = "check_date", DbType = "datetime2")]
		public DateTime? CheckDate { get; set; }

		[JsonProperty, Column(Name = "check_remark", DbType = "nvarchar(MAX)")]
		public string CheckRemark { get; set; }

		[JsonProperty, Column(Name = "check_status", DbType = "nvarchar(MAX)")]
		public string CheckStatus { get; set; }

		[JsonProperty, Column(Name = "checker_id")]
		public long? CheckerId { get; set; }

		[JsonProperty, Column(Name = "checker_name", DbType = "nvarchar(MAX)")]
		public string CheckerName { get; set; }

		[JsonProperty, Column(Name = "creator_id")]
		public long CreatorId { get; set; }

		[JsonProperty, Column(Name = "creator_name", DbType = "nvarchar(MAX)")]
		public string CreatorName { get; set; }

		[JsonProperty, Column(Name = "delete_flag")]
		public byte DeleteFlag { get; set; }

		[JsonProperty, Column(Name = "file_size")]
		public long FileSize { get; set; }

		[JsonProperty, Column(Name = "file_size_display", DbType = "nvarchar(MAX)")]
		public string FileSizeDisplay { get; set; }

		[JsonProperty, Column(Name = "file_suffix", DbType = "nvarchar(MAX)")]
		public string FileSuffix { get; set; }

		[JsonProperty, Column(Name = "group_name", DbType = "nvarchar(MAX)")]
		public string GroupName { get; set; }

		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		[JsonProperty, Column(Name = "md5_code", DbType = "nvarchar(MAX)")]
		public string Md5Code { get; set; }

		[JsonProperty, Column(Name = "original_url", DbType = "nvarchar(MAX)")]
		public string OriginalUrl { get; set; }

		[JsonProperty, Column(Name = "path_to_folder", DbType = "nvarchar(MAX)")]
		public string PathToFolder { get; set; }

		[JsonProperty, Column(Name = "path_to_index", DbType = "nvarchar(MAX)")]
		public string PathToIndex { get; set; }

		[JsonProperty, Column(Name = "resource_desc", DbType = "nvarchar(MAX)")]
		public string ResourceDesc { get; set; }

		[JsonProperty, Column(Name = "resource_duration")]
		public int? ResourceDuration { get; set; }

		[JsonProperty, Column(Name = "resource_level", DbType = "nvarchar(MAX)")]
		public string ResourceLevel { get; set; }

		[JsonProperty, Column(Name = "resource_name", DbType = "nvarchar(MAX)")]
		public string ResourceName { get; set; }

		[JsonProperty, Column(Name = "resource_tags_display", DbType = "nvarchar(MAX)")]
		public string ResourceTagsDisplay { get; set; }

		[JsonProperty, Column(Name = "resource_type", DbType = "nvarchar(MAX)")]
		public string ResourceType { get; set; }

		[JsonProperty, Column(Name = "SCORM_version", DbType = "nvarchar(MAX)")]
		public string SCORMVersion { get; set; }

		[JsonProperty, Column(Name = "t_create", DbType = "datetime2")]
		public DateTime TCreate { get; set; }

		[JsonProperty, Column(Name = "t_modified", DbType = "datetime2")]
		public DateTime TModified { get; set; }

		[JsonProperty, Column(Name = "thumbnail_path", DbType = "nvarchar(MAX)")]
		public string ThumbnailPath { get; set; }

		[JsonProperty, Column(Name = "title_from_manifest", DbType = "nvarchar(MAX)")]
		public string TitleFromManifest { get; set; }

		[JsonProperty, Column(Name = "transf_type", DbType = "nvarchar(MAX)")]
		public string TransfType { get; set; }

		[JsonProperty, Column(Name = "transform_url", DbType = "nvarchar(MAX)")]
		public string TransformUrl { get; set; }


        #region 外键 => 导航属性，OneToMany

        [Navigate("ResourceId")]
        public virtual List<TResourceTagRef> t_resource_tag_refs { get; set; }

        #endregion

        #region 外键 => 导航属性，ManyToMany

        #endregion
    }

}
