//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace CoursewareModifyTool.Model.Courseware
{

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_knowledge_tag")]
	public partial class TKnowledgeTag {

		[JsonProperty, Column(Name = "delete_flag")]
		public byte DeleteFlag { get; set; }

		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		[JsonProperty, Column(Name = "original_id")]
		public long OriginalId { get; set; }

		[JsonProperty, Column(Name = "t_create", DbType = "datetime2")]
		public DateTime TCreate { get; set; }

		[JsonProperty, Column(Name = "t_modified", DbType = "datetime2")]
		public DateTime TModified { get; set; }

	    [JsonProperty, Column(Name = "tag", DbType = "nvarchar(MAX)")]
	    public string Tag { get; set; } = string.Empty;


        #region 外键 => 导航属性，OneToMany

        [Navigate("TagId")]
        public virtual List<TResourceTagRef> t_resource_tag_refs { get; set; }

        #endregion

        #region 外键 => 导航属性，ManyToMany

        #endregion
    }

}
