//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace PracticeBus.Entity {

	/// <summary>
	/// 知识点、技能点等标签信息
	/// </summary>
	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_knowledge_tag")]
	public partial class TKnowledgeTag {

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "create_time", DbType = "datetime")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 删除标识
		/// </summary>
		[JsonProperty, Column(Name = "delete_flag", DbType = "tinyint(2)")]
		public sbyte? DeleteFlag { get; set; }

		/// <summary>
		/// ID
		/// </summary>
		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 源ID
		/// </summary>
		[JsonProperty, Column(Name = "src_id")]
		public long? SrcId { get; set; }

		/// <summary>
		/// 标签名称
		/// </summary>
		[JsonProperty, Column(Name = "tag", DbType = "varchar(50)")]
		public string Tag { get; set; } = string.Empty;

		/// <summary>
		/// 修改时间
		/// </summary>
		[JsonProperty, Column(Name = "update_time", DbType = "datetime")]
		public DateTime? UpdateTime { get; set; }

	}

}
