//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace PracticeBus.Entity {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_subject_bus_statistics")]
	public partial class TSubjectBusStatistics {

	    /// <summary>
	    /// 逻辑删除
	    /// </summary>
	    [JsonProperty, Column(Name = "delete_flag")]
	    public sbyte DeleteFlag { get; set; }

	    /// <summary>
	    /// 完成人数
	    /// </summary>
	    [JsonProperty, Column(Name = "finish_num", DbType = "int(11) unsigned zerofill")]
	    public int FinishNum { get; set; }

	    /// <summary>
	    /// 完成率
	    /// </summary>
	    [JsonProperty, Column(Name = "finish_percent", DbType = "decimal(15,0) unsigned zerofill")]
	    public decimal FinishPercent { get; set; }

	    /// <summary>
	    /// 主键
	    /// </summary>
	    [JsonProperty, Column(Name = "id", IsIdentity = true)]
	    public long Id { get; set; }

	    /// <summary>
	    /// 通过人数
	    /// </summary>
	    [JsonProperty, Column(Name = "pass_num")]
	    public int PassNum { get; set; }

	    /// <summary>
	    /// 通过率
	    /// </summary>
	    [JsonProperty, Column(Name = "pass_percent", DbType = "decimal(15,0) unsigned zerofill")]
	    public decimal PassPercent { get; set; }

	    /// <summary>
	    /// 培训计划id
	    /// </summary>
	    [JsonProperty, Column(Name = "plan_id", DbType = "bigint(20) unsigned zerofill")]
	    public long PlanId { get; set; }

	    /// <summary>
	    /// 科目业务id
	    /// </summary>
	    [JsonProperty, Column(Name = "subject_bus_id")]
	    public long SubjectBusId { get; set; }

	    /// <summary>
	    /// 科目名
	    /// </summary>
	    [JsonProperty, Column(Name = "subject_name", DbType = "varchar(200)")]
	    public string SubjectName { get; set; } = string.Empty;

	    /// <summary>
	    /// 科目资源id
	    /// </summary>
	    [JsonProperty, Column(Name = "subject_original_id")]
	    public long SubjectOriginalId { get; set; }

	    /// <summary>
	    /// 创建时间
	    /// </summary>
	    [JsonProperty, Column(Name = "t_create", DbType = "datetime", ServerTime = DateTimeKind.Local, CanUpdate = false)]
	    public DateTime TCreate { get; set; }

	    /// <summary>
	    /// 修改时间
	    /// </summary>
	    [JsonProperty, Column(Name = "t_modify", DbType = "datetime", ServerTime = DateTimeKind.Local)]
	    public DateTime? TModify { get; set; }

    }

}
