//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace PracticeBus.Entity {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_subject_bus")]
	public partial class TSubjectBus {

		/// <summary>
		/// 训练分类
		/// </summary>
		[JsonProperty, Column(Name = "classify_key", DbType = "varchar(20)")]
		public string ClassifyKey { get; set; } = string.Empty;

		/// <summary>
		/// 训练分类
		/// </summary>
		[JsonProperty, Column(Name = "classify_value", DbType = "varchar(50)")]
		public string ClassifyValue { get; set; } = string.Empty;

		/// <summary>
		/// 创建人id
		/// </summary>
		[JsonProperty, Column(Name = "creator_id")]
		public long CreatorId { get; set; }

		/// <summary>
		/// 创建人名
		/// </summary>
		[JsonProperty, Column(Name = "creator_name", DbType = "varchar(50)")]
		public string CreatorName { get; set; } = string.Empty;

		/// <summary>
		/// 逻辑删除
		/// </summary>
		[JsonProperty, Column(Name = "delete_flag")]
		public sbyte DeleteFlag { get; set; }

		/// <summary>
		/// 训练科目描述
		/// </summary>
		[JsonProperty, Column(Name = "description", DbType = "text")]
		public string Description { get; set; } = string.Empty;

		/// <summary>
		/// 期望结果
		/// </summary>
		[JsonProperty, Column(Name = "expect_result", DbType = "text")]
		public string ExpectResult { get; set; } = string.Empty;

		/// <summary>
		/// 自增主键
		/// </summary>
		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 训练科目名称
		/// </summary>
		[JsonProperty, Column(Name = "name", DbType = "varchar(200)")]
		public string Name { get; set; } = string.Empty;

		/// <summary>
		/// 编号
		/// </summary>
		[JsonProperty, Column(Name = "number", DbType = "varchar(100)")]
		public string Number { get; set; } = string.Empty;

		/// <summary>
		/// 原始表id
		/// </summary>
		[JsonProperty, Column(Name = "original_id")]
		public long OriginalId { get; set; }

		/// <summary>
		/// 机型value
		/// </summary>
		[JsonProperty, Column(Name = "plane_type_value", DbType = "varchar(20)")]
		public string PlaneTypeValue { get; set; } = string.Empty;

		/// <summary>
		/// 机型key
		/// </summary>
		[JsonProperty, Column(Name = "plane_type_key", DbType = "varchar(20)")]
		public string PlaneTypeKey { get; set; } = string.Empty;

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "t_create", ServerTime = DateTimeKind.Local, CanUpdate = false)]
		public DateTime TCreate { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[JsonProperty, Column(Name = "t_modified", ServerTime = DateTimeKind.Local)]
		public DateTime? TModified { get; set; }

		/// <summary>
		/// 知识点展示
		/// </summary>
		[JsonProperty, Column(Name = "tag_display", DbType = "varchar(200)")]
		public string TagDisplay { get; set; } = string.Empty;

		/// <summary>
		/// 任务id
		/// </summary>
		[JsonProperty, Column(Name = "task_bus_id")]
		public long TaskBusId { get; set; }

		/// <summary>
		/// 版本
		/// </summary>
		[JsonProperty, Column(Name = "version")]
		public int Version { get; set; }

	}

}
