//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace PracticeBus.Entity {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_subject_bus_score")]
	public partial class TSubjectBusScore {

		/// <summary>
		/// 逻辑删除
		/// </summary>
		[JsonProperty, Column(Name = "delete_flag")]
		public sbyte DeleteFlag { get; set; }

		/// <summary>
		/// 主键
		/// </summary>
		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 科目原始id
		/// </summary>
		[JsonProperty, Column(Name = "original_id")]
		public long OriginalId { get; set; }

	    /// <summary>
	    /// 培训计划id
	    /// </summary>
	    [JsonProperty, Column(Name = "plan_id")]
	    public long? PlanId { get; set; }

        /// <summary>
        /// 结果 0通过 1未通过
        /// </summary>
        [JsonProperty, Column(Name = "result")]
		public sbyte? Result { get; set; }

		/// <summary>
		/// 状态 0完成 1未完成
		/// </summary>
		[JsonProperty, Column(Name = "status")]
		public sbyte? Status { get; set; }

		/// <summary>
		/// 科目id
		/// </summary>
		[JsonProperty, Column(Name = "subject_bus_id")]
		public long SubjectBusId { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "t_create", DbType = "datetime", ServerTime = DateTimeKind.Local, CanUpdate = false)]
		public DateTime TCreate { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[JsonProperty, Column(Name = "t_modified", DbType = "datetime", ServerTime = DateTimeKind.Local)]
		public DateTime? TModified { get; set; }

		/// <summary>
		/// 任务id
		/// </summary>
		[JsonProperty, Column(Name = "task_bus_id")]
		public long TaskBusId { get; set; }

		/// <summary>
		/// 任务成绩表id
		/// </summary>
		[JsonProperty, Column(Name = "task_score_id")]
		public long TaskScoreId { get; set; }

		/// <summary>
		/// 用户id
		/// </summary>
		[JsonProperty, Column(Name = "user_id")]
		public long UserId { get; set; }

	}

}
