//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace PracticeBus.Entity {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_task_bus_statistics")]
	public partial class TTaskBusStatistics {

        /// <summary>
        /// 本次任务完成人数
        /// </summary>
        [JsonProperty, Column(Name = "attend_num", DbType = "int(11) unsigned zerofill")]
        public int AttendNum { get; set; }

        /// <summary>
        /// 逻辑删除
        /// </summary>
        [JsonProperty, Column(Name = "delete_flag", DbType = "tinyint(3) unsigned zerofill")]
        public sbyte DeleteFlag { get; set; }

        /// <summary>
        /// 平均时长(小时)
        /// </summary>
        [JsonProperty, Column(Name = "duration_avg", DbType = "decimal(15,0) unsigned zerofill")]
        public decimal DurationAvg { get; set; }

        /// <summary>
        /// 总时长(小时)
        /// </summary>
        [JsonProperty, Column(Name = "duration_total", DbType = "decimal(15,0) unsigned zerofill")]
        public decimal DurationTotal { get; set; }

        /// <summary>
        /// 完成率
        /// </summary>
        [JsonProperty, Column(Name = "finish_percent", DbType = "decimal(15,0) unsigned zerofill")]
        public decimal FinishPercent { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [JsonProperty, Column(Name = "id", IsIdentity = true)]
        public long Id { get; set; }

        /// <summary>
        /// 通过率
        /// </summary>
        [JsonProperty, Column(Name = "pass_percent", DbType = "decimal(15,0) unsigned zerofill")]
        public decimal PassPercent { get; set; }

        /// <summary>
        /// 培训计划id
        /// </summary>
        [JsonProperty, Column(Name = "plan_id", DbType = "bigint(20) unsigned zerofill")]
        public long PlanId { get; set; }

        /// <summary>
        /// 本次任务下的科目数
        /// </summary>
        [JsonProperty, Column(Name = "subject_num", DbType = "int(11) unsigned zerofill")]
        public int SubjectNum { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [JsonProperty, Column(Name = "t_create", DbType = "datetime", ServerTime = DateTimeKind.Local, CanUpdate = false)]
        public DateTime TCreate { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [JsonProperty, Column(Name = "t_modify", DbType = "datetime", ServerTime = DateTimeKind.Local)]
        public DateTime? TModify { get; set; }

        /// <summary>
        /// 任务业务id
        /// </summary>
        [JsonProperty, Column(Name = "task_bus_id")]
        public long TaskBusId { get; set; }

        /// <summary>
        /// 任务名
        /// </summary>
        [JsonProperty, Column(Name = "task_name", DbType = "varchar(200)")]
        public string TaskName { get; set; } = string.Empty;

        /// <summary>
        /// 任务资源id
        /// </summary>
        [JsonProperty, Column(Name = "task_original_id")]
        public long TaskOriginalId { get; set; }

    }

}
