//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace PracticeBus.Entity {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_task_bus_score")]
	public partial class TTaskBusScore {

		/// <summary>
		/// 逻辑删除
		/// </summary>
		[JsonProperty, Column(Name = "delete_flag")]
		public sbyte DeleteFlag { get; set; }

		/// <summary>
		/// 所属部门
		/// </summary>
		[JsonProperty, Column(Name = "department", DbType = "varchar(50)")]
		public string Department { get; set; } = string.Empty;

		/// <summary>
		/// 持续时长(秒)
		/// </summary>
		[JsonProperty, Column(Name = "duration", DbType = "int(11) unsigned zerofill")]
		public int Duration { get; set; }

		/// <summary>
		/// 结束时间
		/// </summary>
		[JsonProperty, Column(Name = "end_time", DbType = "datetime")]
		public DateTime? EndTime { get; set; }

		/// <summary>
		/// 主键
		/// </summary>
		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 培训计划id
		/// </summary>
		[JsonProperty, Column(Name = "plan_id", DbType = "bigint(20) unsigned zerofill")]
		public long PlanId { get; set; }

		/// <summary>
		/// 训练结果 0通过 1未通过
		/// </summary>
		[JsonProperty, Column(Name = "result")]
		public sbyte? Result { get; set; }

		/// <summary>
		/// 开始时间
		/// </summary>
		[JsonProperty, Column(Name = "start_time", DbType = "datetime")]
		public DateTime? StartTime { get; set; }

		/// <summary>
		/// 训练状态 0完成 1未完成
		/// </summary>
		[JsonProperty, Column(Name = "status")]
		public sbyte? Status { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "t_create", ServerTime = DateTimeKind.Local, CanUpdate = false)]
		public DateTime TCreate { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[JsonProperty, Column(Name = "t_modify", DbType = "datetime", ServerTime = DateTimeKind.Local)]
		public DateTime? TModify { get; set; }

		/// <summary>
		/// 训练任务id
		/// </summary>
		[JsonProperty, Column(Name = "task_bus_id")]
		public long TaskBusId { get; set; }

		/// <summary>
		/// 人员id
		/// </summary>
		[JsonProperty, Column(Name = "user_id")]
		public long UserId { get; set; }

		/// <summary>
		/// 学员名字
		/// </summary>
		[JsonProperty, Column(Name = "user_name", DbType = "varchar(50)")]
		public string UserName { get; set; } = string.Empty;

	}

}
