//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace PracticeBus.Entity {

	/// <summary>
	/// 参与培训的学员
	/// </summary>
	[JsonObject(MemberSerialization.OptIn), Table(Name = "t_trainingplan_stu")]
	public partial class TTrainingplanStu {

		/// <summary>
		/// 飞行时长
		/// </summary>
		[JsonProperty, Column(Name = "actual_duration", DbType = "varchar(20)")]
		public string ActualDuration { get; set; } = string.Empty;

		/// <summary>
		/// 机型
		/// </summary>
		[JsonProperty, Column(Name = "airplane", DbType = "varchar(20)")]
		public string Airplane { get; set; } = string.Empty;

		/// <summary>
		/// 创建人ID
		/// </summary>
		[JsonProperty, Column(Name = "create_by")]
		public long? CreateBy { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "create_time", DbType = "datetime")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 删除标识
		/// </summary>
		[JsonProperty, Column(Name = "delete_flag", DbType = "tinyint(2)")]
		public sbyte? DeleteFlag { get; set; }

		/// <summary>
		/// 部门
		/// </summary>
		[JsonProperty, Column(Name = "department", DbType = "varchar(20)")]
		public string Department { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "education", DbType = "varchar(20)")]
		public string Education { get; set; } = string.Empty;

		/// <summary>
		/// 飞行状态
		/// </summary>
		[JsonProperty, Column(Name = "fly_status", DbType = "varchar(20)")]
		public string FlyStatus { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "id", IsIdentity = true)]
		public long Id { get; set; }

		/// <summary>
		/// 图片路径
		/// </summary>
		[JsonProperty, Column(Name = "photo_path", DbType = "varchar(250)")]
		public string PhotoPath { get; set; } = string.Empty;

		/// <summary>
		/// 技术等级
		/// </summary>
		[JsonProperty, Column(Name = "skill_level", DbType = "varchar(20)")]
		public string SkillLevel { get; set; } = string.Empty;

		/// <summary>
		/// 培训计划ID
		/// </summary>
		[JsonProperty, Column(Name = "trainingplan_id")]
		public long? TrainingplanId { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[JsonProperty, Column(Name = "update_time", DbType = "datetime")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 用户ID
		/// </summary>
		[JsonProperty, Column(Name = "user_id")]
		public long? UserId { get; set; }

		/// <summary>
		/// 用户
		/// </summary>
		[JsonProperty, Column(Name = "user_name", DbType = "varchar(20)")]
		public string UserName { get; set; } = string.Empty;

		/// <summary>
		/// 账户
		/// </summary>
		[JsonProperty, Column(Name = "user_number", DbType = "varchar(20)")]
		public string UserNumber { get; set; } = string.Empty;

	}

}
